### ISSUE TITLE
Error in tutorial?

### ISSUE THREAD

**Issue by JFonnes** [jcamiloangarita/WT#12]
```
from pwptemp.Main import temp_time

#For circulation time = 5 hours
Tdsi, Ta, Tr, Tcsg, Tsr, Tfm,time = temp_time(5, well, tvd, deltaz, zstep)
```

`ValueError: not enough values to unpack (expected 7, got 6)`

**Comment by JFonnes** [comment]
I removed 'time' and now it works :)

**Comment by jcamiloangarita** [comment]
The tutorial posted on [github](https://github.com/pro-well-plan/pwptemp) is updated with the changes made to this repository (it works assuming you have cloned and updated). For using the package through PyPI you should follow the tutorial posted on [pwp package](https://pypi.org/project/pwptemp/).
