### ISSUE TITLE
Wrong version installed through pip

### ISSUE THREAD

**Issue by JFonnes** [jcamiloangarita/WT#13]
Wrong version installed through pip 

Example from pwt.Main: `TypeError: stab_time() takes 0 positional arguments but 4 were given`

**Comment by jcamiloangarita** [comment]
The function stab_time() was modified to work properly in the repository but it has not been released yet (on PyPI), i.e. this function isn't available in the last version v0.0.6. You can check [CHANGELOG](https://github.com/pro-well-plan/pwptemp/blob/master/CHANGELOG.md) to know what features are already available in the package **pwptemp**.

**Comment by JFonnes** [comment]
Thank you for your fast response. Interesting to follow your project.

**Comment by jcamiloangarita** [comment]
Thanks! It's nice to have more people involved into the project (: more features will be added to make it easier contributing.
