### ISSUE TITLE
Why is the instance of the WellTemperature called mw?

### ISSUE THREAD

**Issue by magnusbj** [jcamiloangarita/WT#2]
I don't understand the abbreviation. I thought it meant mud weight, but I couldn't understand why that would be so important.

**Comment by msfazal** [comment]
"mw" is for "my well". It is just the name used, we can use any other name that is "Well 1" or "Well X" etc

**Comment by magnusbj** [comment]
I suggest changing this to a more easily understandable term in a later update

**Comment by jcamiloangarita** [comment]
This term "mw" is not a problem for an user since any name could be used to create a new instance WellTemperature, however it's a very good suggestion because could be better for contributors to understand and improve the code. So the term's name can be changed to "well" (e.g.).
