### ISSUE TITLE
Is it possible to see the step by step calculations?

### ISSUE THREAD

**Issue by magnusbj** [jcamiloangarita/WT#3]
It seems like the calculation is run for a given time in one go. Is it possible to get timesteps before the final calculations, or is the model solved for that exact time? I would like to create a plot with a time slider.

**Comment by magnusbj** [comment]
I made a function to calculate multiple steps
```    res = []
    for time in [.1,.2,.5,1]:
        Tdsi,Ta,Tr,Tcsg,Tsr,Tfm = temp_time(time,mw,tvd,deltaz,zstep)
        res.append(dict(Tdsi=Tdsi,Ta=Ta,Tr=Tr,Tcsg=Tcsg,Tsr=Tsr,Tfm=Tfm))
```
Is there another way?

**Comment by jcamiloangarita** [comment]
The temperature distribution is calculated only for an exact time since deltat is kept constant in order to ensure always the stability for the finite differences procedure. Creating a loop while using the function temp_time (as your example) is a good way to obtain results for several times.

**Comment by magnusbj** [comment]
Thanks. I think it can be a good application to create a function which runs and store results for multiple steps. 
I'm thinking a
```
class Results:
    def __init__()
    def get_time_steps()
    def get_depth_curve()
    def get_parameter_analysis()
```    
The last one shows the effect of the different parameters for a given calculation. I.e. the friction contribution on the annulus temperature, or the effect of the formation temperature on the pipe temperature?

**Comment by jcamiloangarita** [comment]
This is a really good idea, it's now added in the ["To Do" section](https://github.com/pro-well-plan/pwptemp/projects/1) of the project.
