### ISSUE TITLE
Is it possible to see the effects of various physical events?

### ISSUE THREAD

**Issue by magnusbj** [jcamiloangarita/WT#4]
I would like to see what physical event, like friction, flow, compression or other which cause the temperature change. Can I find these in the data?

**Comment by jcamiloangarita** [comment]
For the temperature distribution calculation **pwptemp** involves the geothermal gradient  (this value depends on some properties such as density, and others related to the depth ) and heat source terms for drill pipe and annular (taking into account drill pipe rotation and frictions).

Thermal gradients (geothermal and seawater) and heat source terms could be found in the class WellTemperature from [Input.py](https://github.com/pro-well-plan/pwptemp/blob/master/pwptemp/Input.py)

**Comment by magnusbj** [comment]
After running a simulation, can I see how much the different factors contributed to the temperature profile? So the temperature of fluid in pipe was mostly affected by the heated pipe or friction or xxx?

**Comment by jcamiloangarita** [comment]
This feature is not available at the moment, but it is already added (creating a new function **get_parameter_analysis**) in the ["To Do" section](https://github.com/pro-well-plan/pwptemp/projects/1) of the project.

**Comment by jcamiloangarita** [comment]
[Analysis module](https://github.com/pro-well-plan/pwptemp/blob/master/pwptemp/Analysis.py) was added with param_effect() returning the effect of fluid circulation, heat source terms and the formation temp. on the calculation of the temp. at bottom; and hs_effect() returning the effect of DP rotation and fluid friction on the calculation of the heat source terms. **Note:** the effect is obtained as a percentage.
