### ISSUE TITLE
Where can I find reference to the model used?

### ISSUE THREAD

**Issue by magnusbj** [jcamiloangarita/WT#6]

**Comment by jcamiloangarita** [comment]
Concepts from different papers were used, however **pwptemp** is mainly based on:

1. Zhang, Z., Xiong, Y., & Guo, F. (2018). Analysis of Wellbore Temperature Distribution and Influencing Factors During Drilling Horizontal Wells. Journal of Energy Resources Technology, 140(9), 092901.

2. Chang, X., Zhou, J., Guo, Y., He, S., Wang, L., Chen, Y., ... & Jian, R. (2018). Heat Transfer Behaviors in Horizontal Wells Considering the Effects of Drill Pipe Rotation, and Hydraulic and Mechanical Frictions during Drilling Procedures. Energies, 11(9), 2414.

**Comment by magnusbj** [comment]
Great, thanks
