### ISSUE TITLE
add __init__.py in test folder?

### ISSUE THREAD

**Issue by magnusbj** [jcamiloangarita/WT#8]
In vscode I needed to add a __init__.py file in the test folder to have vscode detect and run the tests.  Not sure how this work in other environments, but solved a problem for me.

**Comment by magnusbj** [comment]
Great to see tests in the project, much easier to run code. What about a test file showing the plot functions?

**Comment by jcamiloangarita** [comment]
Some tests will be added for the **plot** functions and also for the new functions in the [**Analysis module**](https://github.com/pro-well-plan/pwptemp/blob/master/pwptemp/Analysis.py).

**Comment by magnusbj** [comment]
Looking forward to the analysis module
